services:
  r2-lens:
    build: .
    container_name: r2-lens
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
      - "443:443"
    networks:
      - r2-lens-net
    volumes:
      - ./db:/app/data/
    env_file:
      - .env
    command: ["sleep", "infinity"]
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - r2-lens-net
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:

networks:
  r2-lens-net:
    name: r2_lens_net
