development:
  clients:
    default:
      database: r2_lens
      hosts:
        - localhost:27017
      options:
        user: r2_lens_dev
        password: example
        auth_source: r2_lens
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: r2_lens_test
      hosts:
        - localhost:27017
      options:
        user: r2_lens_test
        password: example
        auth_source: r2_lens_test
  options:
    raise_not_found_error: false

test_ci:
  clients:
    default:
      database: r2_lens_test
      hosts:
        - mongodb-test-ci:27017
  options:
    raise_not_found_error: false
